"""Update column names

Revision ID: 61c9582f4923
Revises: 42c2a8476784
Create Date: 2023-11-28 19:32:51.116213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61c9582f4923'
down_revision = '42c2a8476784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('updated_status', sa.String(length=10), nullable=False))
        batch_op.alter_column('part_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('toy_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('statusAfterClick')
        batch_op.drop_column('statusOnClick')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('combination',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('condition1',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('toy1',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('condition2',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('toy2',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('toy2',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('condition2',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('toy1',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('condition1',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('combination',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statusOnClick', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('statusAfterClick', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('toy_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('part_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_status')
        batch_op.drop_column('current_status')

    # ### end Alembic commands ###
